import turtle
wn = turtle.Screen()

wn.title('multicolor square')
anms = turtle.Turtle()
anms.penup()
anms.goto(40,60)
anms.pendown()


anms.color('red')
anms.begin_fill()
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.end_fill()


anms.penup()
anms.forward(150)
anms.pendown()

anms.color('blue')
anms.begin_fill()
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.end_fill()
anms.penup()
anms.forward(150)
anms.pendown()

anms.color('green')
anms.begin_fill()
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.end_fill()

anms.penup()
anms.forward(150)
anms.pendown()

anms.color('yellow')
anms.begin_fill()
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.left(90)
anms.forward(90)
anms.end_fill()

turtle.mainloop()