import  turtle
name = turtle.Screen()
name.bgcolor('white')
youtube = turtle.Turtle()
youtube.speed(0)
youtube.penup()
youtube.goto(-150,0)
youtube.pendown()
youtube.color('red')
youtube.begin_fill()
youtube.forward(300)
youtube.circle(20,90)
youtube.forward(200)
youtube.circle(20,90)
youtube.forward(300)
youtube.circle(20,90)
youtube.forward(200)
youtube.circle(20,90)
youtube.end_fill()
youtube.hideturtle()
tri = turtle.Turtle()
tri.penup()
tri.goto(-10,150)
tri.pendown()
tri.right(90)
tri.color('white')
tri.begin_fill()
tri.forward(60)
tri.left(120)
tri.forward(60)
tri.left(120)
tri.forward(60)
tri.left(120)
tri.end_fill()
tri.hideturtle()

turtle.mainloop()
